version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: _test\.go
        text: SA5011
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/salmonumbrella/notion-cli
