version: 2
project_name: notion
builds:
  - main: ./cmd/notion
    binary: notion
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: notion-cli
    repository:
      owner: salmonumbrella
      name: homebrew-notion-cli
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/salmonumbrella/notion-cli"
    description: "CLI for Notion"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "notion"
