version: 2
project_name: notion
builds:
  - id: darwin
    main: ./cmd/ntn
    binary: ntn
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}

  - id: linux-windows
    main: ./cmd/ntn
    binary: ntn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'


brews:
  - name: notion-cli
    repository:
      owner: salmonumbrella
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/salmonumbrella/notion-cli"
    description: "CLI for Notion API"
    license: "MIT"
    install: |
      bin.install "ntn"
    test: |
      system "#{bin}/ntn", "--help"
