# lefthook.yml
# Pre-commit and pre-push hooks for notion-cli

pre-commit:
  parallel: true
  commands:
    fmt:
      glob: "*.go"
      run: gofumpt -w {staged_files}
      stage_fixed: true
    lint:
      glob: "*.go"
      run: golangci-lint run --new-from-rev=HEAD --timeout 2m
    build:
      glob: "*.go"
      run: go build ./...

pre-push:
  parallel: true
  commands:
    test:
      run: go test ./...
